AttackOrder: {
  shape: class

  -attackRange: integer

  +new(target, gameManager, enemy, behavior): MoveOrder

  +update(dt float): void
  +moveCloseToTarget(dt float): void
  lookAtPosition(targetPosition): void
}

AttackOrder -> Order: extends
