BitmapText: {
  shape: class

  +new(name string, bmfFontData string, content string, alignmentX string, alignmentY string, x integer = 0, y integer = 0, width integer = 0, height integer = 0, rotation float = 0,scale float = 1,color = white): BitmapText

  -font: Font
  -text: Text
  -contentText: string

  +load(): void
  +unload(): void
  +draw(): void
  +getWidth(): integer
  +getHeight(): integer

  +setContent(newContent string): void
}

BitmapText -> Component: extends
