DefendOrder: {
  shape: class

  -defendRange: integer

  +new(target, gameManager, enemy, behavior): DefendOrder

  +update(dt float): void
  +moveCloseToTarget(dt float): void
  lookAtPosition(targetPosition): void
}

DefendOrder -> Order: extends
