Delay: {
  shape: class

  +new(name string): Delay

  -action: function
  -duration: integer = 0
  -elapsedTime: integer = 0

  +update(_ float): void
  +setDelay(waitDuration integer, completedAction function): void
}

Delay -> Component: extends
