MoveOrder: {
  shape: class

  -currentPath: table
  -pathIndex: integer

  +new(target, gameManager, enemy, behavior): AttackOrder

  +update(dt float): void
  +lookAtPosition(targetPosition): void
}

MoveOrder -> Order: extends
