Order: {
  shape: class

  -currentPath: table
  -pathIndex: integer

  +new(enemy, target, gameManager): Order

  +update(dt float): void
  +clearCurrentPath(): void
  +setCurrentPath(path): void
  +getPathNode(): Integer
  +nextNode(): void
  +getCurrentPath(): table
  +lookAtPosition(targetPosition): void
  +moveCloseToTarget(dt float): void
}
