ScreenManager: {
    shape: class

    -windowWidth: integer
    -windowHeight: integer
    -scaleX: float
    -scaleY: float

    +init(width integer, height integer):void
    +reload():void
    +resize():void
    +calculateCenterPointX():integer
    +calculateCenterPointY():integer
    +getWindowWidth():integer
    +getWindowHeight():integer
    +getScaleX():float
    +getScaleY():float
+ScaleValueX(x float): integer
+ScaleValueY(y float): integer
+ScaleUIValueX(x float):integer
+ScaleUIValueY(y float): integer
+clear(r float, g float, b float): void
    -calculateScale():void

}