SplashScreen: {
  shape: class

  -elapsedTime: integer

  +update(dt float): void
}
SplashScreen -> SpriteSheetImage
SplashScreen -> SoundEffect
SplashScreen -> BitmapText
SplashScreen -> Scene: extends
