TowerStatusHeathBar: {
  shape: class

  +new(name string, gameManager GameManager): TowerStatusHeathBar

  -attackerGroup: integer
  -lastAttack: integer
  -healthBarGroup: integer
  -healthBarValue: integer
  -healthBarMaxValue: integer
  -width: integer
  -height: integer
  -offsetX: integer
  -offsetY: integer
  -renderInfo: array
  +load(): void

  +update(dt float): void
  +draw(): void
  +updateUnitAttacker(fromGroup): void
  +getBackgroundRenderColor(group): void
}

TowerStatusHeathBar -> Component: extends
