Vector2: {
  shape: class

  +new(x float, y float): Vector2

  -x: float
  -y: float

  +distance(x2 integer, y2 integer): float
  +normalize(): Vector2

  +offsetPosition(offsetX integer, offsetY integer): Vector2

  +toString(): string
}
